backend:
  name: git-gateway
  branch: main   # Branche où seront stockés les articles

media_folder: "img/uploads"   # Où stocker les images
public_folder: "/img/uploads"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Auteur", name: "author", widget: "string", default: "Clément Lamps" }
      - { label: "Résumé", name: "description", widget: "text" }
      - { label: "Contenu", name: "body", widget: "markdown" }
      - { label: "Image de couverture", name: "thumbnail", widget: "image" }