backend:
  name: github
  repo: Clayton630/QuartzReport
  branch: main

media_folder: "img/uploads"
public_folder: "/img/uploads"

collections:
  - name: "test"
    label: "Test Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Contenu", name: "body", widget: "markdown" }
